### ISSUE TITLE
It works partially

### ISSUE THREAD

**Issue by AmberKian** [mattiasnordin/StataEditor#1]
Thank you a lot for your contribution!
Actually, this plug-in did work at my computer if my Stata commands are all written in English.
But Stata didn't respond if  there is Chinese Characters in the command.
e.g. 
*你好
I guess it is the encoding problem which you have already mentioned.
try to use  File>Save with Encoding...? Failed. Because there is no correct encoding (GBK) for Chinese. What should I do?

*I know Stata14 have overcome this, but, as a poor student, I really can't afford to go that far.....
Should I transfer to Notepad++ or wait for Sublime to support GBK?

**Comment by mattiasnordin** [comment]
I assume you have a Chinese version of Stata. Do you know what type of enoding that is used in that version? If so, I could add an option to the plugin that lets you send code with the right encoding.

**Comment by AmberKian** [comment]
I am so sorry that I didn't reply timely ><
Stata uses GBK encoding for Chinese Characters. 
https://en.wikipedia.org/wiki/GBK
I've already tried Notepad++ with Stata, and it works! But if Chinese is supported in this plug-in, I will definitely switch back to this! 
Thanks again!

**Comment by mattiasnordin** [comment]
In version 0.5.1, I have added the option to supply your own encoding as a setting. Go to Preferences -> Package Settings -> StataEditor -> Settings - User and paste {"character_encoding": "gbk"} and that should do the trick. Please let me know if it works.

**Comment by AmberKian** [comment]
mattiasnordin , hi!
IT WORKS!!!!! Notepad++ Uninstalled.
I'll tell all my colleagues about this exciting update.
It really means a lot to Chinese scholars.
Thank you for your work again.

Best Regards.

**Comment by mattiasnordin** [comment]
Great! It's a shame you can't save the file with gbk encoding, but as long as you don't need to open the do-files in Stata, that doesn't matter.
