### ISSUE TITLE
Suggestion: improved highlighting of globals and datasets

### ISSUE THREAD

**Issue by ArnoLundberg** [mattiasnordin/StataEditor#11]
Hi Mattias, 

I have two suggestions concerning the syntax highlighting:
1. highlight global variables specifically, e.g. in a command like
   `keep if year >= $first_year` 
   `$first_year` is highlighted the same way as `keep` where I would prefer something which is specific to globals
2. specif highlighting for datasets, i.e. highlight strings like `somedataset.dta` specifically 

Thanks very much!

**Comment by mattiasnordin** [comment]
Hi Arno,

Regarding your first suggestion, that should depend on the color scheme you are using. StataEditor assigns a unique category for locals and globals, which is different from `keep` which is in the category for commands. If you're using the default color scheme "Monokai", then they should have different colors (which should be orange for locals and globals). Please let me know if that is not the case.

I do like your second suggestion, which I might add for the next update.

Mattias

**Comment by ArnoLundberg** [comment]
Hi Mattias, 

you are completely right, with Monokai it does work as intended. I modified my color scheme accordingly. 

Thanks for considering my second suggestion! 

Best,
Arno

**Comment by mattiasnordin** [comment]
Great!
