### ISSUE TITLE
Can't install Stata Automation

### ISSUE THREAD

**Issue by marcos-lee** [mattiasnordin/StataEditor#17]
I'm sorry if this isn't the place to be asking about problems with the Stata Automation installation, but I can't seem to find anywhere on the internet someone also having problems with this. I am following the instruction in this website (http://www.stata.com/automation/#createmsapp) to install it, but the command prompt returns me 

C:\Program Files (x86)\Stata13>StataSE /Register
'StataSE' is not recognized as an internal or external command,
operable program or batch file.

I'm using Windows 10, Stata13 and ST3. What should I do?

PS: If this isn't appropriate, please delete.

**Comment by mattiasnordin** [comment]
Try using the instructions for Windows Vista. For some reason that seems to be the right one to use even if you have another operating system.

**Comment by fgreve** [comment]
Hi! I am having the same problem (win10 + Stata14). I already tried the instructions for Win Vista, but when I execute the code (ctrl+D) nothing happens. I don’t know what could be the problem. It could be that I am working with StataMP rather than the SE version? Thank you in advance

**Comment by mattiasnordin** [comment]
To make sure the problem really is automation, try opening the console in Sublime Text and type:
```
import win32com.client
win32com.client.Dispatch ("stata.StataOLEApp")
```
See what kind of output you get. Remember that you need to keep the shortcut you created when following the Vista instructions somewhere (even though you do not use it to launch Stata).
