### ISSUE TITLE
Use of stata_tmp file messes with working directory path

### ISSUE THREAD

**Issue by bauchter-work** [mattiasnordin/StataEditor#2]
Hi, 
This package does nearly everything I could hope for, but with one issue:
What executes in Stata is the following:

```
do c:\users\<my User>\appdata\local\temp\st_stata_temp.tmp
```

However, I've got a multi-directory hierarchical project that bases its embedded relative paths off of that structure.  When launching, its working directory is then c:\users<my User>\appdata\local\temp instead of the original code's working directory.  This is an issue for linking and working with the main project.   

Is there a way to set the working directory to the code's working directory, then run the .tmp file?  That seems like the most likely way to fix.

FYI - I've figured a fairly obvious workaround, which is to try and run it once, let it fail, then manually assign the working directory in that invoked, persistent Stata session.  Running it and other code works after that...

**Comment by mattiasnordin** [comment]
Just to be clear so I don't misunderstand you: Are you saying that the working directory of Sublime Text or Stata is changed after you execute the code?

**Comment by bauchter-work** [comment]
Hey!
I believe the working directory of Stata's window is changed to that of the local temp file that's being executed ON INITIALIZATION.  The references to other .do files within that executing .do file's directory then break (in the case of a hierarchical .do file call).  I think that's what's been happening.  The workaround I've found is to just execute the code (Ctrl+D), let it fail on the inital Stata window creation, and then update that stata session's settings--as that one is specifically linked to SublimeText editing.  I hope that clarifies things.  

Best practice on my end:  I think it's also probably a good idea to define all the paths to specific files within a larger project using one ".doh" or .do header file so that no matter where you are directory wise you'll be accessing the right files within the .do file under development...

**Comment by mattiasnordin** [comment]
hmm, I think I must be missing something. In a standard hierarchical working tree of do-files you would set the directory with the cd command which then will remain the active working directory indefinitely. So, calling do-files from other do-files should not really be a problem. And the do command sent from Sublime to Stata shouldn't really change anything.

But I guess you have some more elaborate ways of defining paths which I don't really get :-)

**Comment by bauchter-work** [comment]
cd hardcoded can be problematic in every .do file in a full project.  Here's a sequence and code snippet that shows the behavior nicely.
First, open a fresh SublimeText session with no Stata active.
Then, open an existing .do file that contains the following:

``` stata
//DEBUG  This command displays forward slash PWD output: disp subinstr("`c(pwd)'","\","/",.)

display "Current PWD Directory is: "
display subinstr("`c(pwd)'","\","/",.)

cd ".."  //Assumes directory up is "<project>/code/" directory

display "Current PWD Directory is:  "
display subinstr("`c(pwd)'","\","/",.)

quietly {
    include "My_Projects_headerCode.doh"  // includes all sorts of project paths, relative or fixed.
}
```

When this is run (default User keystroke Ctrl+D), the working directory that is displayed right out of the chute is the local install folder for sublime

The requested behavior of an editor<-->launcher would be to set the current working directory within Stata to where the .do file-under-edit exists on the drive/network/etc.

Does that make sense?  
I'm not sure how to accomplish this, but that's the idea...

**Comment by mattiasnordin** [comment]
I see now! Just to be clear, the directory is never changed to the %appdata%\local\temp folder, but is rather at the default location of Sublime (such as C:/Program Files/Sublime Text 3), right? My thinking is that it is generally best practice to declare the directory in some master file to avoid any problems if the location of the do-file is changed. However, when doing things a bit quicker, I agree that it could be nice get the relevant directory of the current do-file instead. I'll see if I can do something about this!

**Comment by mattiasnordin** [comment]
I have now released version 0.6.0 which I think takes care of the problem. By default, the path is set to the current directory of the do-file. Alternatively, it can be set to the path of the project. Finally, it is also possible to supply your own default path. Please let me know if this solved your problem.

**Comment by bauchter-work** [comment]
FYI on the new version:  I see that this now inserts a cd command at the very beginning when invoking Stata.  Unfortunately, this doesn't work in Windows -- or perhaps with directories that have spaces in them.  I'm pretty sure the path needs to be surrounded by double quotes in that CD command for it to be compatible with Windows or spaces-in-folder-names.  When doing this command manually with the path enclosed in double quotes, this command executes fine within Stata.

I'm unfortunately surrounded by people who insert spaces in their folder names...  :)

**Comment by mattiasnordin** [comment]
You're right, there was a simple mistake in the code, it should be fixed now!

**Comment by bauchter-work** [comment]
Verified this works under 0.6.2  Thank you!

**Comment by mattiasnordin** [comment]
Great!

**Comment by golferdude** [comment]
I am having this exact issue with the current version (0.10.1)

**Comment by golferdude** [comment]
despite the setting:
"default_path": "current_path"
the stata session always starts in: 
C:\Program Files\Sublime Text 3
