### ISSUE TITLE
stata + markdown

### ISSUE THREAD

**Issue by eborbath** [mattiasnordin/StataEditor#27]
Hi Mattias,

Thanks a lot for this great package! It works very well, and I have been using it for a while.

As you might know, with Stata 15, Stata [supports dynamic documents](https://www.stata.com/new-in-stata/markdown/) with markdown. I wanted to edit your syntax highlighting code, to avoid coloring ```, since I very often use it in the markdown part. However, I can't find the location of [this highlighting file](https://github.com/mattiasnordin/StataEditor/blob/master/StataEditor.tmLanguage) once I install the package through package control on windows 10. I assume it should be somewhere here: `C:\Users\user_name\AppData\Roaming\Sublime Text 3\Packages` , but it's not. Any ideas how to edit the syntax highlights you have specified, once the package is installed?

Thanks!

**Comment by mattiasnordin** [comment]
Thanks!
In Sublime Text 3, packages are no longer extracted, but are run directly from the .sublime-package file. But you can simply copy the highlighting file from github and save it in the folder you indicated. Any changes you make there should override the default settings.
