### ISSUE TITLE
Graphs are not displayed

### ISSUE THREAD

**Issue by garethcao** [mattiasnordin/StataEditor#28]
Dear Mattiasnordin,
Thanks for your great contribution to this plugin. I have met a strange problem as follows: if I open dofile in Sublime Text 3 and run the codes, graphs won't be displayed while all the other results are just as right as usual. These graphs will not be displayed even if I type commands directly in Stata or use do-file editor, as long as I open it with Sublime at the very beginning. However, if I ignore sublime and open dta/do-file with double-click in the traditional way from the very beginning, everyting goes well and graphs could be displayed normally. (So it is not a problem from stata side)
In addtion, I have used StataEditor for nearly many months and did not make any change to Sublime or Stata recently. This problem emerges suddenly and I could not find any potential solution through the Internet. Could you please help answer it ? Thanks a lot.

Furthermore, although graphs could not be displayed, they are actually created, because command such as "graph export" still works.

It seems that this has something to do with the updates of the plugin for Stata 15, as I just tested using my PC and laptop. FYI.

**Comment by aadityadar** [comment]
I have the same issue as @garethcao. Things were working fine before the latest update.

**Comment by acarril** [comment]
I have the same issue, definitely introduced with v0.9.0 as I have been using the plugin for almost a year without something like that happening.

**Comment by mattiasnordin** [comment]
Alright, I'm going to take a look at this as soon as I have time. Which version of Stata are you using?

**Comment by garethcao** [comment]
Thanks. I use Stata 14.





--


在 2018-02-12 17:08:53，"mattiasnordin" <notifications@github.com> 写道：


Alright, I'm going to take a look at this as soon as I have time. Which version of Stata are you using?

**Comment by 2sls** [comment]
I am also experiencing the same issue just recently (had no issues with it previously) - the graph opens for a sub second and then closes. The graph export still works. This is on Stata 13

**Comment by mattiasnordin** [comment]
Ok, so I realized that this issue goes a bit deeper than I had anticipated, and it's something I struggled with when I first developed the plugin. I have therefore decided to roll back the change in version 0.9.0 in the newest releast version (v0.10.0). Therefore, this should no longer be an issue.

**Comment by garethcao** [comment]
According to the Readme, it seems that my plugin version is 0.8.2 while the problem still exists. Anything I can do to fix it? Thanks.

![1518494056 1](https://user-images.githubusercontent.com/22373620/36132874-c292158c-10b4-11e8-8be5-4b99d94a6499.png)

**Comment by mattiasnordin** [comment]
Please update to version 0.10.0 and the problem should hopefully not exist anymore. The update should be available sometime within the next hour.

**Comment by garethcao** [comment]
The problem has been solved. Thanks a lot.

**Comment by mattiasnordin** [comment]
Great!

**Comment by aadityadar** [comment]
V 0.10 resolves this issue. Thank you, Mattias.

**Comment by mattiasnordin** [comment]
Great!
