### ISSUE TITLE
Syntax highlighting broken

### ISSUE THREAD

**Issue by alejandromolnar** [mattiasnordin/StataEditor#3]
Hi Mattias, thanks for your work on StataEditor. FYI, your last update on Nov 20 has broken syntax highlighting around single quotes used to dereference locals. It happens on some lines and not others, not sure why but it might be related to the number of dereferencings on a line.  Let me know if I can provide more info.
Best,
Alejandro

**Comment by mattiasnordin** [comment]
Thanks for letting me know, it should be fixed now!

**Comment by alejandromolnar** [comment]
Working fine now, thank you very much! A.

**Comment by mattiasnordin** [comment]
Great!
