### ISSUE TITLE
Stata Editor Opens a new instance every time and does not execute code

### ISSUE THREAD

**Issue by kprinceing** [mattiasnordin/StataEditor#30]
Hello Matt,

I set up the Stata Automation using the Vista instructions as you suggest. When I try to "do" or "run" my do file, an instance of Stata opens but the code doesn't pass through. When I "do" or "run" again another instance of Stata opens, with the same result.

I'm using Stata 14 and Windows 7.

Any advice?

**Comment by mattiasnordin** [comment]
Does it keep opening new windows or does it stay with two windows after that?

**Comment by kprinceing** [comment]
I find out what causes this problem. I need to uncheck the box in the preference setting of stata do-file editor. The box states that "Edit do-files opened from windows instead of executing them." After un-cheking this box, everything works nicely.

**Comment by mattiasnordin** [comment]
Great!
