### ISSUE TITLE
Running as portable application

### ISSUE THREAD

**Issue by jmseiden** [mattiasnordin/StataEditor#34]
Hi,

Thanks for this awesome package; I've seen it in use and hope to start using it myself. I'm wondering if there is any possibility of running this package on machines without administrative privileges? It seems like everything except the Stata automation piece is possible without admin privileges, but I am guessing, this is not work-around-able. I doubt my IT department will allow me to install it, so wanted to check. Thanks!

**Comment by mattiasnordin** [comment]
Hmm, I'm guessing that would no be possible unfortunately. Stata automation is outside my control as it is something that Stata themselves provide. You can read more on https://www.stata.com/automation/.

**Comment by jmseiden** [comment]
Thanks for the reply! IT relented in the end. Thanks for a great package!

**Comment by mattiasnordin** [comment]
Great!
