### ISSUE TITLE
Nothing happens with ctrl+d

### ISSUE THREAD

**Issue by giseong-kim** [mattiasnordin/StataEditor#35]
I am using Stata14 on Window 10.
I think I have followed the instruction to use StataEditor but it does not work,
When I press ctrl+d, nothing happens and nothing comes up in console.

I have read issues that seem relevant to my problem but they does not help.

I tired following in console then Stata pops up and no error message.

`import win32com.client`
`win32com.client.Dispatch ("stata.StataOLEApp")`

I look forward to your help. Thanks in advance

**Comment by mattiasnordin** [comment]
Have you checked that the path to Stata in the settings is correct?

**Comment by giseong-kim** [comment]
> Have you checked that the path to Stata in the settings is correct?

Yes, I have. 
In settings-user,
	"stata_path": "C:/Users/abcde/fghij/StataMP-64.exe",
	"stata_version": 14,

Also, I have installed pywin32.

**Comment by mattiasnordin** [comment]
Ok, it's been awhile since I worked with this, so I need to refresh my memory on the code when I have time. In the meantime, you don't have any user-specific key bindings that override the use of ctrl+d? If you use some other way of launching Stata (such as alt+d or ctrl+r), you get the same result?

**Comment by giseong-kim** [comment]
> Ok, it's been awhile since I worked with this, so I need to refresh my memory on the code when I have time. In the meantime, you don't have any user-specific key bindings that override the use of ctrl+d? If you use some other way of launching Stata (such as alt+d or ctrl+r), you get the same result?

I changed hot-key for stata execute then it finally works.
Thank you so much for your useful package and kind answer!

**Comment by mattiasnordin** [comment]
Ok, great!
