### ISSUE TITLE
Suggestion: automatically write settings & automation with do-file

### ISSUE THREAD

**Issue by jh-min** [mattiasnordin/StataEditor#39]
Hi,

I wrote a Stata program which automatically writes `StataEditor.sublime-settings` file and registers `the Stata Automation type library`: https://github.com/jh-min/sublime

I think this definitely seems useless to Sublime Text users.
But while introducing this awesome package to Stata users who have never used Sublime Text before (thus who have never imagined about external text editors), the biggest barrier to entry was the installation process.
So I thought that it might be better to automate the installation process--and did it.

After getting `StataEditor` and `Pywin32` via Package Control, **to run Stata (as Administrator) and execute `sublime` will finish the setup process**. I tested this with Stata14/15.1 in Windows 10, also with portable and installed version of Sublime Text.

Thank you for the astonishing package, `StataEditor` made my life a lot better.

**Comment by mattiasnordin** [comment]
Awesome! I added a link to your github page in the readme file.
