### ISSUE TITLE
ctrl+/ to comment or uncomment a line

### ISSUE THREAD

**Issue by bauchter-work** [mattiasnordin/StataEditor#4]
Here's another Enhancement or user-setting toggle suggestion.  I noticed that the keybinding of Sublime Text allows line-by-line commenting out/in by using the default text editor "comment line" syntax keystroke "ctrl+/".  
Problem is, Stata allows both types of line commenting -- the "*" character or the more typical "//" characters.
I prefer the "//" commenting, because this is less of an overloaded character set than the "*" symbol.  So - I'd love it if I could change the "ctrl+/" keystroke to toggle with leading "//" instead.  
Is this something to be added/modified in StataEditor source - or do you know if there's a different place to do it?

Background:  There's some pretty decent "auto-documenting" packages out there such as StatDoc--which require some care/standardization on how files are constructed for a project.  See rule #6 - https://github.com/mas802/statdoc/wiki/Stata-do-file-Style-Guide

Thanks for any info or feature updates!

**Comment by mattiasnordin** [comment]
I agree that it makes sense to use "//" as default. Version 0.6.3 supports this and also changes the syntax highlighting (including partial line comments).

**Comment by bauchter-work** [comment]
Confirmed feature addition.  Absolutely lovely.  Thanks, and have a happy holiday season!

**Comment by mattiasnordin** [comment]
Great, you too!
