### ISSUE TITLE
Stata 17 support?

### ISSUE THREAD

**Issue by LINCH8** [mattiasnordin/StataEditor#48]

**Comment by mattiasnordin** [comment]
I haven't tried it since I don't have access to Stata 17, but I imagine that it will work as well.

**Comment by nicolas-suarez** [comment]
I was coming here to mention this: the package does works with Stata 17. The instructions are the same, I just edited the version, path to Stata and registered the executable, and it worked in the same way as always.

**Comment by nicolas-suarez** [comment]
Confirming that the package works with Stata 19.
